### PR TITLE
I corrected some deprecated things

### PR DESCRIPTION
**Pull request by ollin18**

### CODE REVIEW

**Comment by aviks** [comment]
Hi Olin, 

Thanks for this. This seems to be failing the tests, see here: https://travis-ci.org/Algocircle/Cascadia.jl/builds/207575316

```
WARNING: both AbstractTrees and Gumbo export "children"; uses of it in module Cascadia must be qualified
ERROR: LoadError: UndefVarError: children not defined
 in (::Cascadia.##43#44{Int64,Int64,Bool})(::Gumbo.HTMLElement{:li}) at /home/travis/.julia/v0.5/Cascadia/src/selector.jl:381
 in (::Cascadia.Selector)(::Gumbo.HTMLElement{:li}) at /home/travis/.julia/v0.5/Cascadia/src/selector.jl:10
 in (::Cascadia.##25#26{Cascadia.Selector,Cascadia.Selector})(::Gumbo.HTMLElement{:li}) at /home/travis/.julia/v0.5/Cascadia/src/selector.jl:251
 in (::Cascadia.Selector)(::Gumbo.HTMLElement{:li}) at /home/travis/.julia/v0.5/Cascadia/src/selector.jl:10
 in matchAllInto(::Cascadia.Selector, ::Gumbo.HTMLElement{:HTML}, ::Array{Gumbo.HTMLNode,1}) at /home/travis/.julia/v0.5/Cascadia/src/selector.jl:98
 in matchall(::Cascadia.Selector, ::Gumbo.HTMLElement{:HTML}) at /home/travis/.julia/v0.5/Cascadia/src/selector.jl:91
 in macro expansion; at /home/travis/.julia/v0.5/Cascadia/test/runtests.jl:43 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/travis/.julia/v0.5/Cascadia/test/runtests.jl, in expression starting on line 39
```

**Comment by aviks** [comment]
Hi Olin, will you be able to fix the the test failures?

**Comment by ollin18** [comment]
Hi,  yes I  will fix them. I am just waiting to this wednesday to pass
because of some exams.

**Comment by aviks** [comment]
Ok, sure, no problem. Thanks again, and good luck.

**Comment by aviks** [comment]
Thanks @ollin18 for all your work on this. I've made a few small changes to fix the tests, and merged this manually in https://github.com/Algocircle/Cascadia.jl/commit/5cf2c8410ed5f19e5d47a159be4ff5298046d924

**Pull request closed without merging**
